export default {
    Complaint:{
        title:'投诉举报管理',
        text:'发卡吧非常在乎您的诚信经营，如果有用户投诉您，请您积极与买家进行联系，处理问题。如拖延、拒绝解决用户投诉，我们将严肃处理！ ',
        no:'订单号',
        reason_type:'投诉原因',
        reason:'投诉内容',
        qq:'联系方式',
        status:'状态',
        detail:'详情',
        creat_at:'投诉时间',
     },
     comdetail:{
        detail:'投诉详情',
        text:'发卡吧提示您：在举证说明过程中，请双方文明用语。无理谩骂，人身攻击者，我们将订单判定给对方！！ ',
        textone:'该投诉还未处理',
        texttwo:'该投诉已处理完毕',
        textthree:'处理结果：此订单支持卖家，该订单已解冻！',
        textfour:'判定依据：买家主动撤销投诉。订单已解冻，款项已返回！',
        textfive:'投诉订单',
        textsix:'买家QQ',
        textserve:'投诉时间',
        textsix:'买家QQ',
        content:'详情内容',
        buyers:'买家',
        systemmessage:'系统消息',
        systemtext:'我们已收到买家的投诉请求，请双方文明用语，妥善处理好投诉问题！尽快为您处理！',
        merchants:'商家',
        status:'已处理',
        nostatus:'未处理'
     },
     search:{
        detail:'投诉详情',
        no:'订单编号',
        data:'投诉日期',
        num:'投诉订单',
        tsresult:'投诉原因',
        statusq:'处理状态',
        detail:'详情',
        searchs:'立即查询',
        input:'请输入订单编号',
        status:'已处理',
        nostatus:'未处理',
        deatilts:'查看投诉详情',
        Cancelcomplaint:'撤销投诉',
     },
     addcomplatint:{
        no:'投诉订单 ',
        num:'订单号',
        payment:'付款凭证',
        reasons:'投诉原因',
        qq:'qq',
        moblie:'手机号',
        Complaintsreasons:'投诉内容',
        submit:'提交',
        placone:'请填写你的qq号，虚假号将会被认为恶意投诉',
        plactwo:'用于接收撤销密码，请认真填写',
        placthree:'请填写具体投诉原因',
        
    }
   
}