export default {
    Complaint:{
        title:'Complaint management',
        text:'The card issuing bar is very concerned about your integrity, if there are user complaints you, please actively contact the buyer to deal with the problem. If delay, refuse to solve customer complaint, we will deal with seriously！ ',
        no:'order number',
        reason_type:'Complaints reasons',
        reason:'complaint content',
        qq:'contact',
        status:'status',
        detail:'details',
        creat_at:'Complaints of time'
     },
     comdetail:{
        detail:'Complaint details',
        text:'Card bar prompt you: in the process of proof illustration, please both civilized language. Unreasonable abuse, personal attack, we will order to the other side!! ',
        textone:'The complaint has not been dealt with',
        texttwo:'The complaint has been dealt with',
        textthree:'Processing result: this order supports the seller and the order has been unfrozen！',
        textfour:'Basis of judgment: the buyer cancels the complaint voluntarily. The order has been unfrozen and the payment has been returned',
        textfive:'The complaint order',
        textsix:'Buyers QQ',
        textserve:'Complaints of time',
        textsix:'Buyers QQ',
        content:'Details of the content',
        buyers:'buyers',
        systemmessage:'System message',
        merchants:'merchants',
        systemtext:'We have received the buyers complaint request, please both civilized language, properly handle the complaint! Deal with it as soon as possible!',
        status:'Have to deal with',
        nostatus:'untreated'
    },
    search:{
        detail:'Complaint details',
        no:'order no',
        data:'Date of complaint',
        num:'The complaint order',
        tsresult:'Complaints reasons',
        status:'Processing state',
        detail:'details',
        searchs:'The query',
        input:'Please enter the order number',
        status:'Have to deal with',
        nostatus:'untreated',
        deatilts:'View complaint details',
        Cancelcomplaint:'Cancel the complaint',
     },
     addcomplatint:{
         no:'complaint order',
         num:'order number',
         payment:'Proof of payment',
         reasons:'Complaints reasons',
         qq:'qq',
         moblie:'Mobile phone no',
         Complaintsreasons:'Complaints reasons',
         submit:'submit',
         placone:'Please fill in your qq number, the false number will be regarded as malicious complaints',
         plactwo:'To receive the undo password, please fill in carefully',
         placthree:'Please fill in the specific reason for complaint',
     }
   
}