export default {
    project:{
        Home:'Home',
        contactus:'contact us',
        Orderracking:'Order Tracking',
        Stationnews:'Station news',
        Information:'Basic Information',
        changepass:'change Password',
        signout:"sign out"
     },
     listarr:{
        Information:'General Information',
        controlcenter:'control center',
        basicsettings:'basic settings',
        changePassword:'change Password',
        Verified:'Verified',
        SecuritySettings:'Security Settings',
        Settlementrecords:'Settlement record',
        Transactionmanagement:'Transaction management',
        Recentlysold:'Recently sold',
        Orderrecord:'Order record',
        Channelanalysis:'Channel analysis',
        Incomestatistics:'Income statistics',
        Storemanagement:'Store management',
        Storelink:'Store link',
        Merchantrate:'Merchant rate',
        Complaintmanagement:'Complaint management',
        Businessencyclopedia:'Businessencyclopedia',
        Stationnews:'Station news',
        log:'Login log',
       Addcoupon:'Add coupon',
       Couponmanagement:'Coupon management',

      },
      index:{
        title:'Dear users:',
        wecome:'You are welcome',
        shopid:'Your business id is',
        announcement:'Latest announcement platform',
        more:'To view more',
        usermoney:'Account balance',
        autowithdrawal:'Automatic withdrawal',
        noauto:'The manual withdrawal',
        todaymoney:'Todays income',
        todaydeal:'Clinch a deal today',
        todayka:'The number of CARDS sold today',
        yestmoney:'Yesterday the income',
        yestdeal:'Yesterday to clinch a deal',
        yestka:'The number of CARDS sold yesterday',
        cumulative:'The accumulative withdrawal',
        agocumulative:'Last time of withdrawal',
        agomoney:'Last settlement amount',
        full:'full',
        yuan:'yuan',
        bi:'pen',
        zhang:'zhang',
        realname:'Real-name authentication'
      }
}