export default {
    Income:{
        title:'收益统计',
        plasedate:'选择日期',
        search:'立即查询',
        select:'请选择',
        reset:'重置',
        toatlsell:'总计卖出',
        sellz:'张',
        selly:'元',
        total_origin_amount:'订单总价',
        total_amount:'实际所得',
        total_profit:'纯利润',
        selltext:'售出总商品件数',
        origin_amount_text:'订单总价格',
        total_amount_text:'扣除平台手续费后实际所得',
        total_profit_text:'扣除进价后纯利润（仅供参考）',
        transactionhour:'商品名称',
        ordernum:'订单编号',
        productname:'购买数量',
        Commoditycost:'商品成本',
        money:'商品单价',
        ordertotal:'订单收入',
        pority:'实际利润',
        paymentmethod:'支付方式',
        creat_time:'下单时间',
       
     },
   
}