export default {
    Income:{
        title:'Income statistics',
        plasedate:'Select date',
        select:'please choose',
        search:'Inquire now',
        reset:'reset',
        toatlsell:'Sell in total',
        sellz:'Piece',
        total_origin_amount:'Total order price',
        selly:'$',
        selltext:'The total number of items sold',
        origin_amount_text:'Total order price',
        total_amount_text:'Actual income after deducting the platform fee',
        total_profit_text:'Net profit after deducting the purchase price (for reference only)',
        total_amount:'Actual income',
        total_profit:'Net profit',
        transactionhour:'product name',
        ordernum:'Order number',
        productname:'Purchase quantity',
        Commoditycost:'Commodity cost',
        money:'Commodity price',
        ordertotal:'Order income',
        pority:'Actual profit',
        paymentmethod:'payment method',
        creat_time:'order time',

     },
}