export default {
    coupons:{
        title:'添加优惠券',
        Discount:'折扣面额 ',
        Dollar:'元',
        distext:'批发的商户请选择“百分比”的折扣面额，单商品的建议选择“元”的面额。',
        Numbergeneration:'生成数量',
        numtext:'最多一次生成200张',
        Validityperiod:'有效期',
        Singleuse:'限单次使用',
        reuse:'重复使用',
        selectdate:'请选择时间',
        coupontext:'过期优惠券系统将自动清理。',
        Categories:'商品分类',
        allgoods:'全部商品',
        remark:'备注信息',
        Createnow:'立即创建'
     },
     couponslist:{
        title:'优惠券管理',
        select:'请选择',
        all:'全部',
        Used:'已使用',
        Unused:'未使用',
        couponsnum:'请输入优惠券号码',
        search:'立即查询',
        reset:'重置',
        clearall:'清空优惠券',
        couponsnums:'优惠券号码',
        Bindingclassification:'绑定分类',
        Denomination:'面额',
        time:'生成时间',
        Remarks:'备注信息',
        Expiredate:'到期时间',
        management:'管理'
     }
}